apiVersion: v1
kind: Service
metadata:
  name: cicd-integration-service
  namespace: test-prioritization
  labels:
    app: cicd-integration-service
    app.kubernetes.io/name: cicd-integration-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cicd-integration-service

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-integration-service-headless
  namespace: test-prioritization
  labels:
    app: cicd-integration-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cicd-integration-service

